service: ner-api

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221
  apiGateway:
    shouldStartNameWithService: true
  stage: dev
  region: us-east-1
  iam:
    role:
      statements:
      - Effect: 'Allow'
        Action:
          - 'lambda:InvokeFunction'
        Resource: "*"  

package:
  exclude:
    - .npmignore
    - .vscode/**
    - package.json
    - package-lock.json
    - (*).ipynb
    - node_modules/**

functions:
  recognize-named-entites:
    handler: handler.handle_request
    memorySize: 1536
    events:
      - http:
          path: ner
          method: post

plugins:
  - serverless-python-requirements
  - serverless-plugin-warmup
  - serverless-api-gateway-throttling

custom:
  pythonRequirements:
    dockerizePip: true
    slim: true
  # https://github.com/juanjoDiaz/serverless-plugin-warmup  
  warmup:
    twentyFourHoursWarmer:
      enabled: true
      events:
        - schedule: cron(*/5 * ? * * *)
      concurrency: 1
  # https://github.com/DianaIonita/serverless-api-gateway-throttling
  apiGatewayThrottling:
    maxRequestsPerSecond: 1
    maxConcurrentRequests: 1