service: ner-api

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221
  apiGateway:
    shouldStartNameWithService: true
  stage: dev
  region: us-east-1
  # REF: https://www.serverless.com/framework/docs/providers/aws/guide/layers/
  #      https://towardsdatascience.com/quickstart-spacy-on-aws-lambda-up-and-running-in-10-minutes-e347037a0ef8
  layers:
  - arn:aws:lambda:us-east-1:770693421928:layer:Klayers-python38-spacy:30
  - arn:aws:lambda:us-east-1:770693421928:layer:Klayers-python38-spacy_model_en_small:1
  iam:
    role:
      statements:
      - Effect: 'Allow'
        Action:
          - 'lambda:InvokeFunction'
        Resource: "*"  

package:
  exclude:
    - .npmignore
    - .vscode/**
    - package.json
    - package-lock.json
    - (*).ipynb
    - node_modules/**

functions:
  recognize-named-entites:
    handler: handler.handle_request
    memorySize: 1536
    timeout: 30
    events:
      - http:
          path: ner
          method: post

plugins:
  - serverless-python-requirements
  - serverless-plugin-warmup
  - serverless-api-gateway-throttling

custom:
  pythonRequirements:
    dockerizePip: true
    slim: true
    #zip: true
    #noDeploy: []
    #useDownloadCache: true
    #useStaticCache: true    
  # https://github.com/juanjoDiaz/serverless-plugin-warmup  
  warmup:
    twentyFourHoursWarmer:
      enabled: true
      events:
        - schedule: cron(*/5 * ? * * *)
      concurrency: 1
  # https://github.com/DianaIonita/serverless-api-gateway-throttling
  apiGatewayThrottling:
    maxRequestsPerSecond: 1
    maxConcurrentRequests: 1