# It is currently not possible to do nested virtualization (for example, using the --platform linux flag).
# The Windows executor currently only supports Windows containers.
# Running Linux containers on Windows is not possible for now.
# REF: https://circleci.com/docs/using-windows/#known-issues-and-limitations
#      https://circleci.com/blog/building-docker-images-for-multiple-os-architectures/
version: 2.1

orbs:
  win: circleci/windows@5.0 # The Windows orb gives you everything you need to start using the Windows executor.

jobs:
  deploy-dev:
    executor:
      name: win/server-2022 # executor type
      size: large # can be medium, large, xlarge, 2xlarge
      shell: bash.exe

    steps:
      - checkout
      - run: systeminfo
      - run:
          name: Install NodeJS
          command: nvm install 18.16.0 && nvm use 18.16.0
      - run:
          name: Install Serverless Framework
          command: npm install -g serverless
      - run:
          name: Serverless AWS authentication
          command: sls config credentials --provider aws --key $AWS_KEY --secret $AWS_SECRET
      - run:
          name: Deploy Lambda functions
          no_output_timeout: 30m
          command: |
            pwd
            cd $CIRCLE_BRANCH
            HF_TOKEN=$HF_TOKEN sls deploy
      - run:
          name: Export Endpoint URL
          command: |
            pwd
            cd $CIRCLE_BRANCH
            HF_TOKEN= sls info --verbose | grep endpoint | sed 's/endpoint\:\ //g' | awk '{print $1}' > endpoint
      - run:
          name: Echo Endpoint URL
          command: |
            pwd
            cd $CIRCLE_BRANCH
            cat endpoint
      - run:
          name: Test Lambda functions
          command: |
            pwd
            cd $CIRCLE_BRANCH
            curl -X POST -H 'Content-Type: application/json' -d @prompt.json $(cat endpoint)

workflows:
  deploy-dev:
    jobs:
      - deploy-dev:
          filters:
            branches:
              only:
                - flan-t5-xxl-ct2
