version: 2.1

workflows:
  deploy-dev:
    jobs:
      - deploy-dev

jobs:
  deploy-dev:
    resource_class: large
    windows: true
    steps:
      - setup_remote_docker:
          version: 20.10.8
          docker_layer_caching: true
      - run:
          name: Test docker setup
          command: |
            set -x
            docker version
            docker run --rm hello-world
      - checkout
      - run:
          name: Install NodeJS 18
          command: |
            choco install nodejs-lts -y
            node --version
      - run:
          name: Install Serverless Framework
          command: npm install -g serverless
      - run:
          name: Serverless AWS authentication
          command: sls config credentials --provider aws --key %AWS_KEY% --secret %AWS_SECRET%
          environment:
            AWS_KEY: ${{ secrets.AWS_KEY }}
            AWS_SECRET: ${{ secrets.AWS_SECRET }}
      - run:
          name: Deploy Lambda functions
          command: |
            pwd
            cd $CIRCLE_BRANCH
            sls deploy
      - run:
          name: Export Endpoint URL
          command: |
            pwd
            cd $CIRCLE_BRANCH
            sls info --verbose | grep endpoint | sed s/endpoint\:\ //g | awk '{print $1}' > endpoint
      - run:
          name: Echo Endpoint URL
          command: |
            pwd
            cd $CIRCLE_BRANCH
            type endpoint
      - run:
          name: Test Lambda functions
          command: |
            pwd
            cd $CIRCLE_BRANCH
            curl -X POST -H 'Content-Type: application/json' -d @prompt.json $(type endpoint)
