version: 2.1

jobs:
  deploy-dev:
    machine: true
    resource_class: large
    steps:
      - checkout
      - run:
          name: Install Serverless Framework
          command: npm install -g serverless
      - run:
          name: Serverless AWS authentication
          command: sls config credentials --provider aws --key $AWS_KEY --secret $AWS_SECRET
      - run:
          name: Deploy Lambda functions
          no_output_timeout: 30m
          command: |
            pwd
            cd $CIRCLE_BRANCH
            HF_TOKEN=$HF_TOKEN sls deploy
      - run:
          name: Export Endpoint URL
          command: |
            pwd
            cd $CIRCLE_BRANCH
            HF_TOKEN= sls info --verbose | grep endpoint | sed 's/endpoint\:\ //g' | awk '{print $1}' > endpoint
      - run:
          name: Echo Endpoint URL
          command: |
            pwd
            cd $CIRCLE_BRANCH
            cat endpoint
      - run:
          name: Test Lambda functions
          command: |
            pwd
            cd $CIRCLE_BRANCH
            curl -X POST -H 'Content-Type: application/json' -d @prompt.json $(cat endpoint)

workflows:
  deploy-dev:
    when: false
    jobs:
      - deploy-dev:
          filters:
            branches:
              only:
                - flan-t5-xl-ct2
