service: gpt4all-llama

frameworkVersion: "3"

provider:
  name: aws
  # REF: https://www.serverless.com/blog/container-support-for-lambda
  ecr:
    # In this section you can define images that will be built locally and uploaded to ECR
    images:
      appimage:
        path: ./
  stage: dev
  region: ap-southeast-1
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "lambda:InvokeFunction"
          Resource: "*"

functions:
  chat:
    image:
      name: appimage
    memorySize: 4096
    timeout:
      900
      # https://www.serverless.com/framework/docs/providers/aws/guide/functions#lambda-function-urls
    url:
      # Allow CORS for all requests from any origin
      cors:
        allowedOrigins:
          - "*"
          #- https://url1.com
          #- https://url2.com
        allowedMethods:
          - POST
