service: california-housing

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221
  stage: dev
  region: us-east-1
  iam:
    role:
      statements:
      - Effect: 'Allow'
        Action:
          - 'lambda:InvokeFunction'
        Resource: "*"

package:
  exclude:
    - .npmignore
    - .vscode/**
    - package.json
    - package-lock.json
    - (*).ipynb
    - node_modules/**

functions:
  predict-price:
    handler: handler.predict
    memorySize: 512
    warmup: true
    events:
      - http:
          path: /get-price
          method: get
          request:
            parameters:
              queryStrings:
                medInc: true
                houseAge: true
                aveRooms: true
                aveBedrms: true
                population: true
                aveOccup: true
                latitude: true
                longitude: true
                
plugins:
  - serverless-python-requirements
  - serverless-plugin-warmup
  
custom:
  pythonRequirements:
    dockerizePip: true
    slim: true 

