service: california-housing

frameworkVersion: '2'

provider:
  name: aws
  apiGateway:
    shouldStartNameWithService: true
  runtime: python3.8
  lambdaHashingVersion: 20201221
  stage: dev
  region: us-east-1
  iam:
    role:
      statements:
      - Effect: 'Allow'
        Action:
          - 'lambda:InvokeFunction'
        Resource: "*"

package:
  exclude:
    - .npmignore
    - .vscode/**
    - package.json
    - package-lock.json
    - (*).ipynb
    - node_modules/**

functions:
  predict-price:
    handler: handler.predict
    memorySize: 512
    events:
      - http:
          path: /get-price
          method: get
          request:
            parameters:
              querystrings:
                medInc: true
                houseAge: true
                aveRooms: true
                aveBedrms: true
                population: true
                aveOccup: true
                latitude: true
                longitude: true

plugins:
  - serverless-python-requirements
  - serverless-plugin-warmup
  - serverless-api-gateway-throttling

custom:
  pythonRequirements:
    dockerizePip: true
    slim: true
  # https://github.com/juanjoDiaz/serverless-plugin-warmup  
  warmup:
    twentyFourHoursWarmer:
      enabled: true
      events:
        - schedule: cron(*/5 * ? * * *)
      concurrency: 1
  # https://github.com/DianaIonita/serverless-api-gateway-throttling
  apiGatewayThrottling:
    maxRequestsPerSecond: 1
    maxConcurrentRequests: 1
